{% set name = "textual-textarea" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/textual_textarea-{{ version }}.tar.gz
  sha256: 7aa9834b5a6defb38eefbff7ffd4234d2a457e7a9d26cfadcbcd504db6c6a6c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8.0
    - textual >=0.27.0,<1.0.0
    - pyperclip >=1.8.2,<2.0.0

test:
  imports:
    - textual_textarea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/textual-textarea
  summary: A text area (multi-line input) with syntax highlighting for Textual
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
