{% set name = "textual-textarea" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textual_textarea-{{ version }}.tar.gz
  sha256: 1343604a4dc3bac0337c58d926a02ddcf451956fb12532a3d5ade9219905f426

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - textual >=0.89.1,<2.0
    - pyperclip >=1.9.0,<2.0.0

test:
  imports:
    - textual_textarea
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tconbeer/textual-textarea
  summary: A text area (multi-line input) with syntax highlighting for Textual
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
