{% set name = "textual-textarea" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/textual_textarea-{{ version }}.tar.gz
  sha256: dcba95eaa2a8a57fd13ce535ca7ce735e887cea5eb34bf6d0f96cd990baf151e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8.0
    - textual >=0.48.1,<1.0.0
    - pyperclip >=1.8.2,<2.0.0
    - tree_sitter_languages <1.10.0

test:
  imports:
    - textual_textarea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/textual-textarea
  summary: A text area (multi-line input) with syntax highlighting for Textual
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
