schema_version: 1

context:
  name: textual-textarea
  version: "0.18.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/textual_textarea-${{ version }}.tar.gz
  sha256: d95f96ef88ea8856c5644717498c11decbeeab4b6d02e8124fc6bd4c511c7481

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - textual >=7.3.0,<9
    - pyperclip >=1.9.0,<2
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - textual_textarea

about:
  summary: A text area (multi-line input) with syntax highlighting for Textual
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tconbeer/textual-textarea

extra:
  recipe-maintainers:
    - xhochy
