schema_version: 1

context:
  name: textual-textarea
  version: 0.17.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/textual_textarea-${{ version }}.tar.gz
  sha256: be27de85017540c75244ca2459d7046c74b479ae45538b5c178623c0845e06d0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - textual >=6.4.0,<7
    - pyperclip >=1.9.0,<2
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - textual_textarea

about:
  summary: A text area (multi-line input) with syntax highlighting for Textual
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tconbeer/textual-textarea

extra:
  recipe-maintainers:
    - xhochy
